<!-- 
filename: footer.inc
author: Anh Tuan Doan
created: 10/5/2022
last modified: 29/5/2022
description: footer element for all pages
-->
<footer id="footer-section">
    <p>This is a website made by .JPEG team. Our members include: </p>
    <div class="images-container">
        <section class="box">
            <figure class="imagebox">
                <img src="images/tuan-picture.jpeg" alt="Tuan's picture">
            </figure>
            <article class="content">
                <h1>Anh Tuan Doan</h1>
                <p>
                    <a href="mailto:103526745@student.swin.edu.au">103526745@student.swin.edu.au</a>
                </p>
            </article>
        </section>
        <section class="box">
            <figure class="imagebox">
                <img src="images/gabe-picture.jpg" alt="Gabriel's picture">
            </figure>
            <article class="content">
                <h1>Gabriel Chee</h1>
                <p>
                    <a href="mailto:103994164@student.swin.edu.au">103994164@student.swin.edu.au</a>
                </p>
            </article>
        </section>
        <section class="box">
            <figure class="imagebox">
                <img src="images/mitch.jpg" alt="Mitch's picture">
            </figure>
            <article class="content">
                <h1>Mitch Anderson</h1>
                <p>
                    <a href="mailto:103314584@student.swin.edu.au">103314584@student.swin.edu.au</a>

                </p>
            </article>
        </section>
        <section class="box">
            <figure class="imagebox">
                <img src="images/andrew.jpg" alt="Andrew's picture">
            </figure>
            <article class="content">
                <h1>Andrew Grivas</h1>
                <p>
                    <a href="mailto:103997406@student.swin.edu.au">103997406@student.swin.edu.au</a>
                </p>
            </article>
        </section>
        <section class="box">
            <figure class="imagebox">
                <img src="images/anthony.jpg" alt="Anthony's picture">
            </figure>
            <article class="content">
                <h1>Anthony Krueger</h1>
                <p>
                    <a href="mailto:103562710@student.swin.edu.au">103562710@student.swin.edu.au</a>
                </p>
            </article>
        </section>
    </div>
</footer>